# Generated by Django 4.1.1 on 2022-10-10 19:53

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingWith',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', tinymce.models.HTMLField()),
                ('image_link', models.CharField(max_length=250)),
                ('url', models.CharField(max_length=250)),
            ],
        ),
    ]
