# Generated by Django 4.1.1 on 2022-11-03 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_workingwith'),
    ]

    operations = [
        migrations.AddField(
            model_name='workingwith',
            name='support',
            field=models.BooleanField(default=False),
        ),
    ]
