# Generated by Django 4.1.1 on 2022-11-05 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_workingwith_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='workingwith',
            name='image_alt_text',
            field=models.CharField(default='image', max_length=100),
        ),
    ]
